name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Extract changelog for release
        id: changelog
        run: |
          # Extract the latest version from CHANGELOG.md
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracting changelog for version $VERSION"
          
          # Get changelog section for this version
          awk -v version="$VERSION" '
            /^## \[/ { 
              if ($0 ~ "\\[" version "\\]") { 
                found=1; next 
              } else if (found) { 
                exit 
              } 
            }
            found && /^## \[/ { exit }
            found { print }
          ' CHANGELOG.md > release_notes.md
          
          echo "Release notes:"
          cat release_notes.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 🎉 Release ${{ github.ref }}
          body_path: release_notes.md
          draft: false
          prerelease: false

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.ref == 'refs/heads/main'
